apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: ${{ values.component_id }}
  name: ${{ values.component_id }}
spec:
  port:
    targetPort: ${{values.http_port}}-tcp
  subdomain: ${{ values.component_id }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ${{ values.component_id }}
    weight: 100
