apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${{ values.component_id }}
  name: ${{ values.component_id }}
spec:
  ports:
  - name: ${{ values.http_port}}-tcp
    port: ${{ values.http_port}}
    protocol: TCP
    targetPort: ${{ values.http_port}}
  selector:
    app: ${{ values.component_id }}
  type: ClusterIP
