apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{ values.component_id }}
  name: ${{ values.component_id }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ${{ values.component_id }}
  template:
    metadata:
      labels:
        app: ${{ values.component_id }}
    spec:
      containers:
      - image: imageName
        name: ${{ values.component_id }}
        ports:
        - containerPort: 8080
          protocol: TCP
