apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  backstage.io/kubernetes-id: ${{ values.component_id }}

resources:
  - ${{values.component_id}}-deploy.yaml
  - ${{values.component_id}}-service.yaml
  - ${{values.component_id}}-route.yaml
